# Generated by Django 5.0.6 on 2024-05-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_author_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
